[package]
name = "ecc"
version = "0.1.1"
edition = "2018"
authors = ["Craig Warner"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hamming = {path = "hamming"}
rand = "0.8.4"
clap = { version = "2.0.0"}
